### PR TITLE
Fix #2 and Fix #19 Improve compatibility with Forge mods

### LINKED ISSUE #2: BitBucket: Scrolling in JEI while in inventory moves items between inventories.
Old issue link: https://bitbucket.org/YaLTeR/mouse-tweaks/issues/14/scrolling-in-jei-while-in-inventory-moves

### LINKED ISSUE #17: Unexpected inventory transfer while opening GUI
Way to reproduce

Make a chest and open it's GUI
Move cursor to an item to make sure that cursor pointing on an item while open GUI again.
Close GUI, scroll down the mouse wheel for some length
Open GUI. Found the item which pointing on has been transfered.

### LINKED ISSUE #19: Shift click issue with JEI and Quark
Steps to reproduce the bug:
 * Create a Minecraft instance with Forge, MouseTweaks, JEI, and Quark (and AutoRegLib, a Quark dependency).
 * Start a creative-mode world.
 * Open a crafting table and fill your inventory with items cheated from JEI.
    * 
 * Open a crafting recipe that can be shift-clicked into the crafting table, the [+] button must be above an item in your inventory if the recipe gui was not open.
    * 
 * Shift click the [+] button and observe extra items are moved into the crafting grid.
    * 

Quark moves items into the crafting grid with its "Better Craft Shifting" feature, but there is no conflict between just JEI and Quark. 
Mouse Tweaks must be present to cause the issue seen here, if it's not there then the shift-click puts the recipe into the crafting table without any extra items.

I do not know why this is happening, so I am hoping to try to figure it out with you and @vazkii

### PR DESCRIPTION
**Pull request by mezz**
This fixes #2 where Mouse Tweaks would scroll "through" the JEI gui to affect the gui behind.
This fixes #19 where Mouse Tweaks would handle mouse clicks that were already being handled by a Forge mod.
Edit: this also fixes #17

### CODE REVIEW

File: src/main/java/yalter/mousetweaks/MouseState.java [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+	private final EnumSet<MouseButton> pressedButtons = EnumSet.noneOf(MouseButton.class);
+	private int scrollAmount = 0;
+
+	public MouseState() {}
+
+	/**
+	 * Update the current mouse state.
+	 */
+	public void update() {
+		MouseButton eventButton = getEventButton();
```
Comment (YaLTeR) [inline src/main/java/yalter/mousetweaks/MouseState.java]: Are we guaranteed to get multiple update calls from Forge even if multiple buttons were pressed at once? Even if so, there doesn't seem to be any special handling in the LiteLoader code—think pressing or releasing LMB and RMB at the same time.

Comment (mezz) [reply src/main/java/yalter/mousetweaks/MouseState.java]: Vanilla consumes the mouse buttons one at a time, and Forge fires an event for each one.

I tested with pressing LMB and RMB at the same time, this code handles it and `Main` uses something like `if (right) elseif (left) else` so it will not try to do 2 things at once, it will just use the right button if both are pressed.

Comment (YaLTeR) [reply src/main/java/yalter/mousetweaks/MouseState.java]: I guess this is more of a concern for release: press RMB, then press LMB, then release both at once. With a low enough FPS this can easily happen. Will the LiteLoader code work correctly in this case or will the mod think one of the buttons got stuck pressed?

Comment (mezz) [reply src/main/java/yalter/mousetweaks/MouseState.java]: I think you're right and it could be an issue, I'll take a look.

Comment (mezz) [reply src/main/java/yalter/mousetweaks/MouseState.java]: I pushed a fix, it will check `Mouse.isButtonDown` to confirm anything that `MouseState` thinks is pressed.
This way `MouseState` can still prevent using buttons from previous guis, and we get real confirmation that it doesn't have some "stuck" button.

**Comment by YaLTeR** [comment]
I will take a look and merge later today, I've an exam to take care of in 2 hours :sweat_smile:

**Comment by mezz** [comment]
Exams come first, it has been broken for ages anyway :)
Thanks!

**Comment by YaLTeR** [comment]
In my quick test with LiteLoader and 60 FPS (not low), the RMB dragging is registered about 50% of the times. I'm not doing anything weird like pressing two buttons at once.

**Comment by YaLTeR** [comment]
Is reworking MT to use `onGuiMouseInput` in Forge part of the fix too, as in does Forge not deliver this event if some other mod handles it?

**Comment by mezz** [comment]
`onGuiMouseInput` is mainly used to detect multiple mouse inputs per frame. I used the `Post` event to allow guis or mods to cancel the event before MT gets it, but in practice the event is very rarely canceled.

I’ll look into the LiteLoader issue. One solution might be to have separate `MouseState` for Forge and LL so that this change only has an effect with Forge and things work exactly the same on LL. What do you think?

**Comment by YaLTeR** [comment]
I need to better understand how this method of obtaining mouse input works. If mods rarely cancel events then how does it prevent MT catching clicks through a JEI overlay?

**Comment by mezz** [comment]
I click issue wasn’t really that mouse tweaks clicked through, but that it was handling a click that started in the previously open GUI (same as issue #17).
JEI overlay is a different GUI, and we clear the mouse state when a new GUI is opened. So a click or click-and-hold that starts in the JEI GUI gets ignored and the bug is fixed.

**Comment by YaLTeR** [comment]
According to #2 if they scroll while JEI is open on a spot that would correspond to a slot under JEI it registers that input on the slot under JEI. Although I think it's more of an incorrect current screen handling in MT as opposed to incorrect mouse handling.

**Comment by mezz** [comment]
It turned out that it wasn't actually scrolling through the GUI, it was just applying scroll immediately after the new GUI opened. So the scrolling issue was also fixed by clearing the mouse state.

**Comment by mezz** [comment]
I just tested and there is no issue with clicking through the JEI GUI with this PR.

**Comment by mezz** [comment]
One issue remains: LiteLoader is not able to detect all the mouse events.
I think the best solution for this is to have LiteLoader work the same as before, so I will work on implementing that. 
It will still have the minor bug from #17, but there aren't so many mod conflicts there so the JEI issues can probably be safely ignored.

**Comment by YaLTeR** [comment]
I'm just thinking that maybe there's a simpler solution without reworking the mouse buttons and adding a forge event. Like #6?

**Comment by mezz** [comment]
It looks like the solution from #6 will consume mouse events. By doing that, other mods cannot respond to them, so I don't think it's a very good solution.

**Comment by mezz** [comment]
I think this should be all set now, I don't have further changes to make to it.

**Comment by YaLTeR** [comment]
Issues I found after a quick testing session:
- When running on just LiteLoader, right clicking and dragging doesn't place the item into the slot you clicked, only in the next slots.
- When running on LiteLoader + Forge with Forge OnTick method if you scroll items very quickly most scrolls are ignored.
- When running on LiteLoader + Forge with LiteLoader OnTick method scrolling once results in it scrolling the whole stack rapidly.

Once again, I'm not sure I fully understand the interaction between the mods which causes the initial issue. You're saying that a simple fix from #6 won't do because "other mods can't respond to mouse events", but that isn't an issue currently and it doesn't seem that that change would affect the state of affairs?

**Comment by mezz** [comment]
Thanks for testing, I will work harder on getting this to work correctly.

Explaining this is going to be a bit long-winded and I apologize in advance for that, but I will do my best.

### Mouse Event Handling:
Mouse actions come in as a stream of events like: 
`mouse button 1 pressed`, `mouse button 1 released`, `mouse button 2 pressed`, etc

Vanilla Minecraft consumes these events in order, and Forge hooks into this and fires its own event for each of these actions so that mods can subscribe to the events they are interested in using.

On a GUI that is shared by multiple mods, whoever has higher priority can read the mouse event and then cancel it so that anyone with lower priority does not see that particular mouse event. This makes it so that one mod "consumes" a mouse clicked and unclicked event, and that system prevents two or more mods from responding to the same mouse event.

### Mouse State Polling:
MouseTweaks is checking mouse state once each render tick, it is not directly handling each mouse event.
This has some disadvantages:
- If there is a low FPS and someone clicks quickly, the state could be the same at frame 1 and frame 2 and the click is not detected at all. By contrast, Minecraft (and the Forge events that hook into it) consume every mouse event that happened in each frame in the order they are created, which allows handling of multiple events per frame. 
- MouseTweaks will not see when a mod cancels a mouse event, the mouse state is the same even if someone else used the event.

### Issues with existing solution
The simple fix from #6 will completely consume the mouse wheel for everyone any time the GUI changes. 
This impacts the mouse state directly, bypassing the vanilla system, and assumes nobody else might want to use that mouse wheel information.

It fixes the issue for scrolling when a new GUI opens, but it does not fix the issue for clicking. If it was extended to also consume mouse events, it would make it so that other mods would never see those mouse events, and could put mods in a bad state where they detected a mouse clicked event but never see the mouse unclicked event because it was consumed blindly by MouseTweaks when a GUI changed.

### Proposed Solution
The solution I have proposed here is to keep a separate mouse state that is just for MouseTweaks, that uses the mouse events from Forge when available. 
(When I get it working properly!) it will be able to:
 - React to all mouse events, even at low FPS
 - Ignore mouse events that are already being used by Forge mods
 - Clear the mouse state *just for MouseTweaks* when a new GUI is opened, without impacting the vanilla system or other mods.

**Comment by mezz** [comment]
I have tested and pushed fixes for the issues you found. 
Thanks!

**Comment by mezz** [comment]
We could make it so that 1 frame can only consume a small fixed amount from the forge mouse state. That way the scroll action is spread out over more frames, but that could be unpleasant at low FPS. 
You may want to try tweaking it to your preference, I’m not sure what rate would feel best.

**Comment by YaLTeR** [comment]
> We could make it so that 1 frame can only consume a small fixed amount from the forge mouse state. That way the scroll action is spread out over more frames, but that could be unpleasant at low FPS.

No, that just adds input lag, making it even worse.

I see that the mouse input events are posted from `GuiScreen.handleInput()` which is called every client tick (rather than render tick). I'm assuming there's no way to grab events from elsewhere? How do other subsystems get input every render tick, like non-GUI inputs (walking, etc.) or tooltips which update their position every frame?

**Comment by mezz** [comment]
Ah I see what you mean now.

Mouse position is always available without consuming it, so tooltips use the data every frame. 

I’m not sure how the non-GUI inputs are handled but it’s probably polling the mouse state and hoping FPS is high enough to not drop inputs.

Generally GUI inputs need to be very accurate and don’t need to be handled super smoothly, but I see why scrolling would be an exception. 

I will have to look more closely at how vanilla handles scrolling in their GUIs. There is a trade-off here and if you want it to be as smooth as possible it may be better to handle the scrolling like in #6 even though it will be less friendly to other mods.

**Comment by YaLTeR** [comment]
Well, vanilla scrolling in e.g. the creative item picker seems to also update only every tick. I suppose there's no way around it if we want to use the input events (and have good mod compatibility). I suppose I can merge this now, and maybe add a setting for mod compatibility vs. smooth scrolling (which switches it back to `Mouse.getDWheel()` for scrolling)? Do you think it can be set to smooth scrolling by default? Doesn't seem like scrolling issues are too easy to come by, but actual scrolling is a very frequent action, so I think it makes sense to optimize that experience first.

**Comment by mezz** [comment]
It’s up to you, that sounds good to me though.

**Comment by mezz** [comment]
Any more thoughts on this @YaLTeR?
I still agree with what you said before.
It seems good to merge now and then later you can add a config for smooth scrolling (and possibly have it enabled by default).

**Comment by YaLTeR** [comment]
Yeah, thanks a lot again for working on this.

**Comment by YaLTeR** [comment]
I uploaded a 2.10 version to CurseForge with the fixes (under a setting).

**Comment by YaLTeR** [comment]
Hm, now that I think of it, I should've only set the scrolling to be affected by the setting, and not the rest of the mouse events.

**Comment by YaLTeR** [comment]
Alright, I did just that and replaced the release.

**Comment by mezz** [comment]
Thanks for carefully working through this bug with me! 
I'm sure most players won't know what was going on here, but lots of people will be happy it's fixed.
